# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_entry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='body_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
        migrations.AddField(
            model_name='entry',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(to='weblog.Category'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='weblog.Tag'),
        ),
    ]
