# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_auto_20160819_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
